<?php
/**
 * @author Tsvetan Stoychev <ceckoslab@gmail.com>
 * @license http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */

$itemId = $this->getRequest()->getParam('item_id');
?>
<form id="order_custom_options_edit_form" action="<?php echo $this->getUrl('extendix_itemoptions/item/update_options', array('item_id' => $itemId)); ?>" method="post">
    <?php echo $this->getChildHtml('product.composite.fieldset'); ?>

    <div class="f-right">
        <button type="button" class="scalable save update-options">
            <span><?php echo $this->__('Update Options') ?></span>
        </button>
    </div>
</form>